# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hakkinda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Hakkinda(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 483)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1201, 451))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 251, 166);\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 250, 1051, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setStyleSheet("font: 10pt \"Gill Sans Ultra Bold\";\n"
"background-color: rgb(194, 255, 135);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("background-color: rgb(234, 255, 221);\n"
"font: 63 8pt \"Bahnschrift SemiBold\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 220, 237);\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 80, 1051, 173))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("font: 10pt \"Gill Sans Ultra Bold\";\n"
"background-color: rgb(194, 255, 135);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setStyleSheet("background-color: rgb(234, 255, 221);\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 63 8pt \"Bahnschrift SemiBold\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 220, 237);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setStyleSheet("background-color: rgb(234, 255, 221);\n"
"font: 63 8pt \"Bahnschrift SemiBold\";\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 220, 237);\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "HAKKINDA"))
        self.lineEdit.setText(_translate("MainWindow", "ÖZELLIKLER"))
        self.label_4.setText(_translate("MainWindow", "Meyve ve sebzelerin stok yönetimi\n"
"Yeni meyve ve sebze kaydı ekleme, güncelleme, silme\n"
"Meyve ve sebzeleri türlerine, adetlerine ve menşe bilgilerine göre arama yapabilme\n"
"Veritabanı ile güvenli veri saklama"))
        self.lineEdit_2.setText(_translate("MainWindow", "HAKKINDA"))
        self.label.setText(_translate("MainWindow", "Bu uygulama, meyve ve sebzelerin stok yönetimini sağlayan bir depo yönetim uygulamasıdır.\n"
" Kullanıcılar, meyve ve sebzelerin türlerini, adetlerini, fiyatlarını ve menşe bilgilerini kaydedebilir, güncelleyebilir, arayabilir ve silebilirler. \n"
" Ayrıca, meyve ve sebzeleri türlerine, adetlerine ve menşe bilgilerine göre arama yapabilirler.\n"
""))
        self.label_3.setText(_translate("MainWindow", "Bu uygulama, PyQt5 kütüphanesi kullanılarak Python programlama dili ile geliştirilmiştir.\n"
" Arayüz tasarımı için Qt Designer kullanılmış, veritabanı işlemleri için SQLite kullanılmıştır."))
