# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Giris(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(180, 10, 431, 541))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 10, 381, 521))
        self.label.setStyleSheet("background-color: rgb(255, 152, 117);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Lneusername = QtWidgets.QLineEdit(self.widget)
        self.Lneusername.setGeometry(QtCore.QRect(110, 210, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lneusername.setFont(font)
        self.Lneusername.setToolTip("")
        self.Lneusername.setStyleSheet("background-color: rgb(255, 232, 220);")
        self.Lneusername.setText("")
        self.Lneusername.setObjectName("Lneusername")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(120, 50, 181, 81))
        self.label_2.setStyleSheet("font: 24pt \"Ravie\";\n"
"background-color: rgb(255, 152, 117);\n"
"")
        self.label_2.setObjectName("label_2")
        self.btnlogin = QtWidgets.QPushButton(self.widget)
        self.btnlogin.setGeometry(QtCore.QRect(110, 410, 211, 61))
        self.btnlogin.setStyleSheet("font: 16pt \"Ravie\";\n"
"background-color: rgb(255, 255, 127);")
        self.btnlogin.setObjectName("btnlogin")
        self.Lnepassword = QtWidgets.QLineEdit(self.widget)
        self.Lnepassword.setGeometry(QtCore.QRect(110, 290, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Lnepassword.setFont(font)
        self.Lnepassword.setToolTip("")
        self.Lnepassword.setStyleSheet("background-color: rgb(255, 232, 220);")
        self.Lnepassword.setObjectName("Lnepassword")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Lneusername.setPlaceholderText(_translate("MainWindow", "  Kullanıcı adı"))
        self.label_2.setText(_translate("MainWindow", "LOG İN"))
        self.btnlogin.setText(_translate("MainWindow", "LOG İN"))
        self.Lnepassword.setPlaceholderText(_translate("MainWindow", "  Kullanıcı şifre"))
